//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:28 AM(foreman)- (JAXB RI IBM 2.2.3-11/28/2011 06:21 AM(foreman)-)
//


package in.co.ntpc.pradip.dop.service;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

@WebService(name = "DOPContentProviderDelegate", targetNamespace = "http://dop.pradip.ntpc.co.in/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface DOPContentProviderDelegate {


    /**
     * 
     * @param arg0
     * @return
     *     returns in.co.ntpc.pradip.dop.service.DopSchema
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getNextPage", targetNamespace = "http://dop.pradip.ntpc.co.in/", className = "in.co.ntpc.pradip.dop.service.GetNextPage")
    @ResponseWrapper(localName = "getNextPageResponse", targetNamespace = "http://dop.pradip.ntpc.co.in/", className = "in.co.ntpc.pradip.dop.service.GetNextPageResponse")
    public DopSchema getNextPage(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @param arg1
     * @param arg2
     * @return
     *     returns java.util.List<java.lang.String>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getRomanClauseBySubClauseAndClauseAndSection", targetNamespace = "http://dop.pradip.ntpc.co.in/", className = "in.co.ntpc.pradip.dop.service.GetRomanClauseBySubClauseAndClauseAndSection")
    @ResponseWrapper(localName = "getRomanClauseBySubClauseAndClauseAndSectionResponse", targetNamespace = "http://dop.pradip.ntpc.co.in/", className = "in.co.ntpc.pradip.dop.service.GetRomanClauseBySubClauseAndClauseAndSectionResponse")
    public List<String> getRomanClauseBySubClauseAndClauseAndSection(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getPageImage", targetNamespace = "http://dop.pradip.ntpc.co.in/", className = "in.co.ntpc.pradip.dop.service.GetPageImage")
    @ResponseWrapper(localName = "getPageImageResponse", targetNamespace = "http://dop.pradip.ntpc.co.in/", className = "in.co.ntpc.pradip.dop.service.GetPageImageResponse")
    public String getPageImage(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<java.lang.String>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getClauseBySection", targetNamespace = "http://dop.pradip.ntpc.co.in/", className = "in.co.ntpc.pradip.dop.service.GetClauseBySection")
    @ResponseWrapper(localName = "getClauseBySectionResponse", targetNamespace = "http://dop.pradip.ntpc.co.in/", className = "in.co.ntpc.pradip.dop.service.GetClauseBySectionResponse")
    public List<String> getClauseBySection(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getPageImage2", targetNamespace = "http://dop.pradip.ntpc.co.in/", className = "in.co.ntpc.pradip.dop.service.GetPageImage2")
    @ResponseWrapper(localName = "getPageImage2Response", targetNamespace = "http://dop.pradip.ntpc.co.in/", className = "in.co.ntpc.pradip.dop.service.GetPageImage2Response")
    public String getPageImage2(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<in.co.ntpc.pradip.dop.service.CustomSearchResult>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "solrSearchResultWithHighlight", targetNamespace = "http://dop.pradip.ntpc.co.in/", className = "in.co.ntpc.pradip.dop.service.SolrSearchResultWithHighlight")
    @ResponseWrapper(localName = "solrSearchResultWithHighlightResponse", targetNamespace = "http://dop.pradip.ntpc.co.in/", className = "in.co.ntpc.pradip.dop.service.SolrSearchResultWithHighlightResponse")
    public List<CustomSearchResult> solrSearchResultWithHighlight(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @param arg1
     * @param arg2
     * @param arg3
     * @return
     *     returns java.util.List<in.co.ntpc.pradip.dop.service.CustomSearchResult>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getResultBasedOnMetaData", targetNamespace = "http://dop.pradip.ntpc.co.in/", className = "in.co.ntpc.pradip.dop.service.GetResultBasedOnMetaData")
    @ResponseWrapper(localName = "getResultBasedOnMetaDataResponse", targetNamespace = "http://dop.pradip.ntpc.co.in/", className = "in.co.ntpc.pradip.dop.service.GetResultBasedOnMetaDataResponse")
    public List<CustomSearchResult> getResultBasedOnMetaData(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3);

    /**
     * 
     * @return
     *     returns java.util.List<java.lang.String>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getDopSection", targetNamespace = "http://dop.pradip.ntpc.co.in/", className = "in.co.ntpc.pradip.dop.service.GetDopSection")
    @ResponseWrapper(localName = "getDopSectionResponse", targetNamespace = "http://dop.pradip.ntpc.co.in/", className = "in.co.ntpc.pradip.dop.service.GetDopSectionResponse")
    public List<String> getDopSection();

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getTotalPages", targetNamespace = "http://dop.pradip.ntpc.co.in/", className = "in.co.ntpc.pradip.dop.service.GetTotalPages")
    @ResponseWrapper(localName = "getTotalPagesResponse", targetNamespace = "http://dop.pradip.ntpc.co.in/", className = "in.co.ntpc.pradip.dop.service.GetTotalPagesResponse")
    public String getTotalPages(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns in.co.ntpc.pradip.dop.service.DopSchema
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getPreviousPage", targetNamespace = "http://dop.pradip.ntpc.co.in/", className = "in.co.ntpc.pradip.dop.service.GetPreviousPage")
    @ResponseWrapper(localName = "getPreviousPageResponse", targetNamespace = "http://dop.pradip.ntpc.co.in/", className = "in.co.ntpc.pradip.dop.service.GetPreviousPageResponse")
    public DopSchema getPreviousPage(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns in.co.ntpc.pradip.dop.service.DopSchema
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCurrentPage", targetNamespace = "http://dop.pradip.ntpc.co.in/", className = "in.co.ntpc.pradip.dop.service.GetCurrentPage")
    @ResponseWrapper(localName = "getCurrentPageResponse", targetNamespace = "http://dop.pradip.ntpc.co.in/", className = "in.co.ntpc.pradip.dop.service.GetCurrentPageResponse")
    public DopSchema getCurrentPage(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @param arg1
     * @return
     *     returns java.util.List<java.lang.String>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getSubClauseByClauseAndSection", targetNamespace = "http://dop.pradip.ntpc.co.in/", className = "in.co.ntpc.pradip.dop.service.GetSubClauseByClauseAndSection")
    @ResponseWrapper(localName = "getSubClauseByClauseAndSectionResponse", targetNamespace = "http://dop.pradip.ntpc.co.in/", className = "in.co.ntpc.pradip.dop.service.GetSubClauseByClauseAndSectionResponse")
    public List<String> getSubClauseByClauseAndSection(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

}
